
name: Linux Mainline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: sudo apt-get install gcc g++ make unzip -y;

      - name: Download Source
        run: cd /tmp; wget https://github.com/ammarfaizi2/linux-block/archive/refs/heads/master.zip;

      - name: Build
        run: |
          cd /tmp && \
          unzip master.zip && \
          ls -l;
