
name: Linux Mainline (test-uaf)

on:
  push:
    branches: [ build ]
  pull_request:
    branches: [ build ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get install gcc g++ clang make unzip flex bison zstd \
            build-essential libelf-dev -y && \
          gcc --version && \
          make --version;

      - name: Download Source
        run: |
          mkdir -pv /tmp/build && \
          cd /tmp/build && \
          wget -q https://github.com/ammarfaizi2/linux-block/archive/refs/heads/master.zip && \
          nproc;

      - name: Extract Source
        run: |
          cd /tmp/build && \
          unzip master.zip >> /dev/null && \
          mv linux-block-master linux;

      - name: Download Config
        run: |
          cd /tmp/build/linux && \
          wget -q https://raw.githubusercontent.com/ammarfaizi2/linux-build/master/config/test-uaf.txt -O .config && \
          make olddefconfig -j4 && \
          head -n30 .config;

      - name: Build
        run: |
          cd /tmp/build/linux && \
          make deb-pkg -j4;

      - name: List File
        run: |
          cd /tmp/build && \
          ls -la && \
          cd /tmp/build/linux && \
          ls -la;

      # - name: Download a Build Artifact
      #   uses: actions/download-artifact@v2.0.10
      #   with:
      #     name: Linux
      #     path: 
